[package]
name = "harness"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
lazy_static = "1.4.0"
regex = "1.5.4"
typescript_rust = { path = "../typescript_rust" }
typescript_services_rust = { path = "../typescript_services_rust" }

[dev-dependencies]

[lib]
name = "harness"
